# Generated by Django 2.0.6 on 2018-07-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagery', models.ImageField(help_text='upload image', upload_to='')),
                ('message', models.TextField(help_text='description of art')),
            ],
        ),
    ]
